# the location to save the downloaded art
save_art_location: $HOME/.config/awesome/artwork.png
# the shell command to run when done fetching
shell_command: awesome-client "awesome.emit_signal('music::set_cover', '$HOME/.config/awesome/artwork.png')"
# fallback art
fallback: $HOME/.config/awesome/fallback.png